/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GuideArticle {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'publishDate' : bigint,
  'tags' : Array<GuideTag>,
  'author' : string,
  'readTime' : bigint,
  'relatedProductIds' : Array<bigint>,
}
export type GuideTag = { 'styling' : null } |
  { 'thinning' : null } |
  { 'scalpCare' : null } |
  { 'greyHair' : null } |
  { 'products' : null };
export interface Product {
  'id' : bigint,
  'stockStatus' : StockStatus,
  'name' : string,
  'createdAt' : bigint,
  'size' : string,
  'tags' : Array<string>,
  'description' : string,
  'imageUrl' : string,
  'suitableFor' : Array<string>,
  'category' : ProductCategory,
  'benefits' : Array<string>,
  'brand' : string,
  'rating' : number,
  'price' : number,
  'keyIngredients' : Array<string>,
  'reviewCount' : bigint,
}
export type ProductCategory = { 'scalpCare' : null } |
  { 'shampoosAndConditioners' : null } |
  { 'treatmentsAndSerums' : null } |
  { 'stylingTools' : null };
export interface ProductFilter {
  'sortOrder' : [] | [SortOrder],
  'searchTerm' : [] | [string],
  'category' : [] | [ProductCategory],
}
export interface Review {
  'id' : bigint,
  'content' : string,
  'date' : bigint,
  'authorName' : string,
  'productId' : bigint,
  'rating' : number,
}
export type SortOrder = { 'byNewest' : null } |
  { 'byRating' : null } |
  { 'byPrice' : null } |
  { 'byPopularity' : null };
export type StockStatus = { 'inStock' : null } |
  { 'outOfStock' : null } |
  { 'lowStock' : null };
export interface SubscriberPublic {
  'status' : SubscriptionStatus,
  'startedAt' : bigint,
  'planId' : string,
  'stripeSubscriptionId' : string,
  'userId' : Principal,
  'stripeCustomerId' : string,
}
export interface SubscriptionPlan {
  'id' : string,
  'features' : Array<string>,
  'interval' : string,
  'name' : string,
  'description' : string,
  'currency' : string,
  'price' : number,
}
export type SubscriptionStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'inactive' : null };
export interface _SERVICE {
  'cancelMySubscription' : ActorMethod<[], boolean>,
  'createGuideArticle' : ActorMethod<
    [string, string, bigint, string, Array<GuideTag>, Array<bigint>],
    GuideArticle
  >,
  'createProduct' : ActorMethod<
    [
      string,
      string,
      number,
      ProductCategory,
      string,
      string,
      StockStatus,
      Array<string>,
      Array<string>,
      Array<string>,
      string,
      Array<string>,
    ],
    Product
  >,
  'getGuideArticle' : ActorMethod<[bigint], [] | [GuideArticle]>,
  'getMySubscription' : ActorMethod<[], [] | [SubscriberPublic]>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductReviews' : ActorMethod<[bigint], Array<Review>>,
  'getRelatedProducts' : ActorMethod<[bigint, bigint], Array<Product>>,
  'getSubscriptionPlan' : ActorMethod<[string], [] | [SubscriptionPlan]>,
  'isSubscribed' : ActorMethod<[], boolean>,
  'listGuideArticles' : ActorMethod<[[] | [GuideTag]], Array<GuideArticle>>,
  'listProducts' : ActorMethod<[ProductFilter], Array<Product>>,
  'listSubscriptionPlans' : ActorMethod<[], Array<SubscriptionPlan>>,
  'recordSubscription' : ActorMethod<
    [string, string, string],
    SubscriberPublic
  >,
  'submitReview' : ActorMethod<[bigint, string, number, string], Review>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];