/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GuideTag = IDL.Variant({
  'styling' : IDL.Null,
  'thinning' : IDL.Null,
  'scalpCare' : IDL.Null,
  'greyHair' : IDL.Null,
  'products' : IDL.Null,
});
export const GuideArticle = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishDate' : IDL.Int,
  'tags' : IDL.Vec(GuideTag),
  'author' : IDL.Text,
  'readTime' : IDL.Nat,
  'relatedProductIds' : IDL.Vec(IDL.Nat),
});
export const ProductCategory = IDL.Variant({
  'scalpCare' : IDL.Null,
  'shampoosAndConditioners' : IDL.Null,
  'treatmentsAndSerums' : IDL.Null,
  'stylingTools' : IDL.Null,
});
export const StockStatus = IDL.Variant({
  'inStock' : IDL.Null,
  'outOfStock' : IDL.Null,
  'lowStock' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'stockStatus' : StockStatus,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'size' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'suitableFor' : IDL.Vec(IDL.Text),
  'category' : ProductCategory,
  'benefits' : IDL.Vec(IDL.Text),
  'brand' : IDL.Text,
  'rating' : IDL.Float64,
  'price' : IDL.Float64,
  'keyIngredients' : IDL.Vec(IDL.Text),
  'reviewCount' : IDL.Nat,
});
export const SubscriptionStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'inactive' : IDL.Null,
});
export const SubscriberPublic = IDL.Record({
  'status' : SubscriptionStatus,
  'startedAt' : IDL.Int,
  'planId' : IDL.Text,
  'stripeSubscriptionId' : IDL.Text,
  'userId' : IDL.Principal,
  'stripeCustomerId' : IDL.Text,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'date' : IDL.Int,
  'authorName' : IDL.Text,
  'productId' : IDL.Nat,
  'rating' : IDL.Float64,
});
export const SubscriptionPlan = IDL.Record({
  'id' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'interval' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'currency' : IDL.Text,
  'price' : IDL.Float64,
});
export const SortOrder = IDL.Variant({
  'byNewest' : IDL.Null,
  'byRating' : IDL.Null,
  'byPrice' : IDL.Null,
  'byPopularity' : IDL.Null,
});
export const ProductFilter = IDL.Record({
  'sortOrder' : IDL.Opt(SortOrder),
  'searchTerm' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(ProductCategory),
});

export const idlService = IDL.Service({
  'cancelMySubscription' : IDL.Func([], [IDL.Bool], []),
  'createGuideArticle' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(GuideTag),
        IDL.Vec(IDL.Nat),
      ],
      [GuideArticle],
      [],
    ),
  'createProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        ProductCategory,
        IDL.Text,
        IDL.Text,
        StockStatus,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [Product],
      [],
    ),
  'getGuideArticle' : IDL.Func([IDL.Nat], [IDL.Opt(GuideArticle)], ['query']),
  'getMySubscription' : IDL.Func([], [IDL.Opt(SubscriberPublic)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getRelatedProducts' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getSubscriptionPlan' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SubscriptionPlan)],
      ['query'],
    ),
  'isSubscribed' : IDL.Func([], [IDL.Bool], ['query']),
  'listGuideArticles' : IDL.Func(
      [IDL.Opt(GuideTag)],
      [IDL.Vec(GuideArticle)],
      ['query'],
    ),
  'listProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
  'listSubscriptionPlans' : IDL.Func(
      [],
      [IDL.Vec(SubscriptionPlan)],
      ['query'],
    ),
  'recordSubscription' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [SubscriberPublic],
      [],
    ),
  'submitReview' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Text],
      [Review],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GuideTag = IDL.Variant({
    'styling' : IDL.Null,
    'thinning' : IDL.Null,
    'scalpCare' : IDL.Null,
    'greyHair' : IDL.Null,
    'products' : IDL.Null,
  });
  const GuideArticle = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishDate' : IDL.Int,
    'tags' : IDL.Vec(GuideTag),
    'author' : IDL.Text,
    'readTime' : IDL.Nat,
    'relatedProductIds' : IDL.Vec(IDL.Nat),
  });
  const ProductCategory = IDL.Variant({
    'scalpCare' : IDL.Null,
    'shampoosAndConditioners' : IDL.Null,
    'treatmentsAndSerums' : IDL.Null,
    'stylingTools' : IDL.Null,
  });
  const StockStatus = IDL.Variant({
    'inStock' : IDL.Null,
    'outOfStock' : IDL.Null,
    'lowStock' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'stockStatus' : StockStatus,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'size' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'suitableFor' : IDL.Vec(IDL.Text),
    'category' : ProductCategory,
    'benefits' : IDL.Vec(IDL.Text),
    'brand' : IDL.Text,
    'rating' : IDL.Float64,
    'price' : IDL.Float64,
    'keyIngredients' : IDL.Vec(IDL.Text),
    'reviewCount' : IDL.Nat,
  });
  const SubscriptionStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const SubscriberPublic = IDL.Record({
    'status' : SubscriptionStatus,
    'startedAt' : IDL.Int,
    'planId' : IDL.Text,
    'stripeSubscriptionId' : IDL.Text,
    'userId' : IDL.Principal,
    'stripeCustomerId' : IDL.Text,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'date' : IDL.Int,
    'authorName' : IDL.Text,
    'productId' : IDL.Nat,
    'rating' : IDL.Float64,
  });
  const SubscriptionPlan = IDL.Record({
    'id' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'interval' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'currency' : IDL.Text,
    'price' : IDL.Float64,
  });
  const SortOrder = IDL.Variant({
    'byNewest' : IDL.Null,
    'byRating' : IDL.Null,
    'byPrice' : IDL.Null,
    'byPopularity' : IDL.Null,
  });
  const ProductFilter = IDL.Record({
    'sortOrder' : IDL.Opt(SortOrder),
    'searchTerm' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(ProductCategory),
  });
  
  return IDL.Service({
    'cancelMySubscription' : IDL.Func([], [IDL.Bool], []),
    'createGuideArticle' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(GuideTag),
          IDL.Vec(IDL.Nat),
        ],
        [GuideArticle],
        [],
      ),
    'createProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          ProductCategory,
          IDL.Text,
          IDL.Text,
          StockStatus,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [Product],
        [],
      ),
    'getGuideArticle' : IDL.Func([IDL.Nat], [IDL.Opt(GuideArticle)], ['query']),
    'getMySubscription' : IDL.Func([], [IDL.Opt(SubscriberPublic)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getRelatedProducts' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getSubscriptionPlan' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SubscriptionPlan)],
        ['query'],
      ),
    'isSubscribed' : IDL.Func([], [IDL.Bool], ['query']),
    'listGuideArticles' : IDL.Func(
        [IDL.Opt(GuideTag)],
        [IDL.Vec(GuideArticle)],
        ['query'],
      ),
    'listProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
    'listSubscriptionPlans' : IDL.Func(
        [],
        [IDL.Vec(SubscriptionPlan)],
        ['query'],
      ),
    'recordSubscription' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [SubscriberPublic],
        [],
      ),
    'submitReview' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Text],
        [Review],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };