/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SubscriberPublic {
    status: SubscriptionStatus;
    startedAt: bigint;
    planId: string;
    stripeSubscriptionId: string;
    userId: Principal;
    stripeCustomerId: string;
}
export interface Product {
    id: bigint;
    stockStatus: StockStatus;
    name: string;
    createdAt: bigint;
    size: string;
    tags: Array<string>;
    description: string;
    imageUrl: string;
    suitableFor: Array<string>;
    category: ProductCategory;
    benefits: Array<string>;
    brand: string;
    rating: number;
    price: number;
    keyIngredients: Array<string>;
    reviewCount: bigint;
}
export interface GuideArticle {
    id: bigint;
    title: string;
    content: string;
    publishDate: bigint;
    tags: Array<GuideTag>;
    author: string;
    readTime: bigint;
    relatedProductIds: Array<bigint>;
}
export interface SubscriptionPlan {
    id: string;
    features: Array<string>;
    interval: string;
    name: string;
    description: string;
    currency: string;
    price: number;
}
export interface ProductFilter {
    sortOrder?: SortOrder;
    searchTerm?: string;
    category?: ProductCategory;
}
export interface Review {
    id: bigint;
    content: string;
    date: bigint;
    authorName: string;
    productId: bigint;
    rating: number;
}
export enum GuideTag {
    styling = "styling",
    thinning = "thinning",
    scalpCare = "scalpCare",
    greyHair = "greyHair",
    products = "products"
}
export enum ProductCategory {
    scalpCare = "scalpCare",
    shampoosAndConditioners = "shampoosAndConditioners",
    treatmentsAndSerums = "treatmentsAndSerums",
    stylingTools = "stylingTools"
}
export enum SortOrder {
    byNewest = "byNewest",
    byRating = "byRating",
    byPrice = "byPrice",
    byPopularity = "byPopularity"
}
export enum StockStatus {
    inStock = "inStock",
    outOfStock = "outOfStock",
    lowStock = "lowStock"
}
export enum SubscriptionStatus {
    active = "active",
    cancelled = "cancelled",
    inactive = "inactive"
}
export interface backendInterface {
    cancelMySubscription(): Promise<boolean>;
    createGuideArticle(title: string, author: string, readTime: bigint, content: string, tags: Array<GuideTag>, relatedProductIds: Array<bigint>): Promise<GuideArticle>;
    createProduct(name: string, brand: string, price: number, category: ProductCategory, description: string, imageUrl: string, stockStatus: StockStatus, keyIngredients: Array<string>, benefits: Array<string>, suitableFor: Array<string>, size: string, tags: Array<string>): Promise<Product>;
    getGuideArticle(id: bigint): Promise<GuideArticle | null>;
    getMySubscription(): Promise<SubscriberPublic | null>;
    getProduct(id: bigint): Promise<Product | null>;
    getProductReviews(productId: bigint): Promise<Array<Review>>;
    getRelatedProducts(productId: bigint, limit: bigint): Promise<Array<Product>>;
    getSubscriptionPlan(planId: string): Promise<SubscriptionPlan | null>;
    isSubscribed(): Promise<boolean>;
    listGuideArticles(tag: GuideTag | null): Promise<Array<GuideArticle>>;
    listProducts(filter: ProductFilter): Promise<Array<Product>>;
    listSubscriptionPlans(): Promise<Array<SubscriptionPlan>>;
    recordSubscription(planId: string, stripeCustomerId: string, stripeSubscriptionId: string): Promise<SubscriberPublic>;
    submitReview(productId: bigint, authorName: string, rating: number, content: string): Promise<Review>;
}
import type { GuideArticle as _GuideArticle, GuideTag as _GuideTag, Product as _Product, ProductCategory as _ProductCategory, ProductFilter as _ProductFilter, SortOrder as _SortOrder, StockStatus as _StockStatus, SubscriberPublic as _SubscriberPublic, SubscriptionPlan as _SubscriptionPlan, SubscriptionStatus as _SubscriptionStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async cancelMySubscription(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelMySubscription();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelMySubscription();
            return result;
        }
    }
    async createGuideArticle(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: Array<GuideTag>, arg5: Array<bigint>): Promise<GuideArticle> {
        if (this.processError) {
            try {
                const result = await this.actor.createGuideArticle(arg0, arg1, arg2, arg3, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg4), arg5);
                return from_candid_GuideArticle_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGuideArticle(arg0, arg1, arg2, arg3, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg4), arg5);
            return from_candid_GuideArticle_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProduct(arg0: string, arg1: string, arg2: number, arg3: ProductCategory, arg4: string, arg5: string, arg6: StockStatus, arg7: Array<string>, arg8: Array<string>, arg9: Array<string>, arg10: string, arg11: Array<string>): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0, arg1, arg2, to_candid_ProductCategory_n9(this._uploadFile, this._downloadFile, arg3), arg4, arg5, to_candid_StockStatus_n11(this._uploadFile, this._downloadFile, arg6), arg7, arg8, arg9, arg10, arg11);
                return from_candid_Product_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0, arg1, arg2, to_candid_ProductCategory_n9(this._uploadFile, this._downloadFile, arg3), arg4, arg5, to_candid_StockStatus_n11(this._uploadFile, this._downloadFile, arg6), arg7, arg8, arg9, arg10, arg11);
            return from_candid_Product_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGuideArticle(arg0: bigint): Promise<GuideArticle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGuideArticle(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGuideArticle(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySubscription(): Promise<SubscriberPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySubscription();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySubscription();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: bigint): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductReviews(arg0: bigint): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductReviews(arg0);
            return result;
        }
    }
    async getRelatedProducts(arg0: bigint, arg1: bigint): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRelatedProducts(arg0, arg1);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRelatedProducts(arg0, arg1);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubscriptionPlan(arg0: string): Promise<SubscriptionPlan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriptionPlan(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriptionPlan(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async isSubscribed(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isSubscribed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isSubscribed();
            return result;
        }
    }
    async listGuideArticles(arg0: GuideTag | null): Promise<Array<GuideArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGuideArticles(to_candid_opt_n28(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGuideArticles(to_candid_opt_n28(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProducts(arg0: ProductFilter): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts(to_candid_ProductFilter_n30(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts(to_candid_ProductFilter_n30(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSubscriptionPlans(): Promise<Array<SubscriptionPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSubscriptionPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSubscriptionPlans();
            return result;
        }
    }
    async recordSubscription(arg0: string, arg1: string, arg2: string): Promise<SubscriberPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSubscription(arg0, arg1, arg2);
                return from_candid_SubscriberPublic_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSubscription(arg0, arg1, arg2);
            return from_candid_SubscriberPublic_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitReview(arg0: bigint, arg1: string, arg2: number, arg3: string): Promise<Review> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_GuideArticle_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GuideArticle): GuideArticle {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_GuideTag_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GuideTag): GuideTag {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ProductCategory_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCategory): ProductCategory {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_StockStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StockStatus): StockStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriberPublic_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriberPublic): SubscriberPublic {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatus): SubscriptionStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GuideArticle]): GuideArticle | null {
    return value.length === 0 ? null : from_candid_GuideArticle_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SubscriberPublic]): SubscriberPublic | null {
    return value.length === 0 ? null : from_candid_SubscriberPublic_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SubscriptionPlan]): SubscriptionPlan | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    stockStatus: _StockStatus;
    name: string;
    createdAt: bigint;
    size: string;
    tags: Array<string>;
    description: string;
    imageUrl: string;
    suitableFor: Array<string>;
    category: _ProductCategory;
    benefits: Array<string>;
    brand: string;
    rating: number;
    price: number;
    keyIngredients: Array<string>;
    reviewCount: bigint;
}): {
    id: bigint;
    stockStatus: StockStatus;
    name: string;
    createdAt: bigint;
    size: string;
    tags: Array<string>;
    description: string;
    imageUrl: string;
    suitableFor: Array<string>;
    category: ProductCategory;
    benefits: Array<string>;
    brand: string;
    rating: number;
    price: number;
    keyIngredients: Array<string>;
    reviewCount: bigint;
} {
    return {
        id: value.id,
        stockStatus: from_candid_StockStatus_n15(_uploadFile, _downloadFile, value.stockStatus),
        name: value.name,
        createdAt: value.createdAt,
        size: value.size,
        tags: value.tags,
        description: value.description,
        imageUrl: value.imageUrl,
        suitableFor: value.suitableFor,
        category: from_candid_ProductCategory_n17(_uploadFile, _downloadFile, value.category),
        benefits: value.benefits,
        brand: value.brand,
        rating: value.rating,
        price: value.price,
        keyIngredients: value.keyIngredients,
        reviewCount: value.reviewCount
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _SubscriptionStatus;
    startedAt: bigint;
    planId: string;
    stripeSubscriptionId: string;
    userId: Principal;
    stripeCustomerId: string;
}): {
    status: SubscriptionStatus;
    startedAt: bigint;
    planId: string;
    stripeSubscriptionId: string;
    userId: Principal;
    stripeCustomerId: string;
} {
    return {
        status: from_candid_SubscriptionStatus_n23(_uploadFile, _downloadFile, value.status),
        startedAt: value.startedAt,
        planId: value.planId,
        stripeSubscriptionId: value.stripeSubscriptionId,
        userId: value.userId,
        stripeCustomerId: value.stripeCustomerId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: string;
    publishDate: bigint;
    tags: Array<_GuideTag>;
    author: string;
    readTime: bigint;
    relatedProductIds: Array<bigint>;
}): {
    id: bigint;
    title: string;
    content: string;
    publishDate: bigint;
    tags: Array<GuideTag>;
    author: string;
    readTime: bigint;
    relatedProductIds: Array<bigint>;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        publishDate: value.publishDate,
        tags: from_candid_vec_n6(_uploadFile, _downloadFile, value.tags),
        author: value.author,
        readTime: value.readTime,
        relatedProductIds: value.relatedProductIds
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inStock: null;
} | {
    outOfStock: null;
} | {
    lowStock: null;
}): StockStatus {
    return "inStock" in value ? StockStatus.inStock : "outOfStock" in value ? StockStatus.outOfStock : "lowStock" in value ? StockStatus.lowStock : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scalpCare: null;
} | {
    shampoosAndConditioners: null;
} | {
    treatmentsAndSerums: null;
} | {
    stylingTools: null;
}): ProductCategory {
    return "scalpCare" in value ? ProductCategory.scalpCare : "shampoosAndConditioners" in value ? ProductCategory.shampoosAndConditioners : "treatmentsAndSerums" in value ? ProductCategory.treatmentsAndSerums : "stylingTools" in value ? ProductCategory.stylingTools : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    cancelled: null;
} | {
    inactive: null;
}): SubscriptionStatus {
    return "active" in value ? SubscriptionStatus.active : "cancelled" in value ? SubscriptionStatus.cancelled : "inactive" in value ? SubscriptionStatus.inactive : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    styling: null;
} | {
    thinning: null;
} | {
    scalpCare: null;
} | {
    greyHair: null;
} | {
    products: null;
}): GuideTag {
    return "styling" in value ? GuideTag.styling : "thinning" in value ? GuideTag.thinning : "scalpCare" in value ? GuideTag.scalpCare : "greyHair" in value ? GuideTag.greyHair : "products" in value ? GuideTag.products : value;
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GuideArticle>): Array<GuideArticle> {
    return value.map((x)=>from_candid_GuideArticle_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GuideTag>): Array<GuideTag> {
    return value.map((x)=>from_candid_GuideTag_n7(_uploadFile, _downloadFile, x));
}
function to_candid_GuideTag_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GuideTag): _GuideTag {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_ProductCategory_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): _ProductCategory {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_ProductFilter_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductFilter): _ProductFilter {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_SortOrder_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOrder): _SortOrder {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_StockStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StockStatus): _StockStatus {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GuideTag | null): [] | [_GuideTag] {
    return value === null ? candid_none() : candid_some(to_candid_GuideTag_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sortOrder?: SortOrder;
    searchTerm?: string;
    category?: ProductCategory;
}): {
    sortOrder: [] | [_SortOrder];
    searchTerm: [] | [string];
    category: [] | [_ProductCategory];
} {
    return {
        sortOrder: value.sortOrder ? candid_some(to_candid_SortOrder_n32(_uploadFile, _downloadFile, value.sortOrder)) : candid_none(),
        searchTerm: value.searchTerm ? candid_some(value.searchTerm) : candid_none(),
        category: value.category ? candid_some(to_candid_ProductCategory_n9(_uploadFile, _downloadFile, value.category)) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): {
    scalpCare: null;
} | {
    shampoosAndConditioners: null;
} | {
    treatmentsAndSerums: null;
} | {
    stylingTools: null;
} {
    return value == ProductCategory.scalpCare ? {
        scalpCare: null
    } : value == ProductCategory.shampoosAndConditioners ? {
        shampoosAndConditioners: null
    } : value == ProductCategory.treatmentsAndSerums ? {
        treatmentsAndSerums: null
    } : value == ProductCategory.stylingTools ? {
        stylingTools: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StockStatus): {
    inStock: null;
} | {
    outOfStock: null;
} | {
    lowStock: null;
} {
    return value == StockStatus.inStock ? {
        inStock: null
    } : value == StockStatus.outOfStock ? {
        outOfStock: null
    } : value == StockStatus.lowStock ? {
        lowStock: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GuideTag): {
    styling: null;
} | {
    thinning: null;
} | {
    scalpCare: null;
} | {
    greyHair: null;
} | {
    products: null;
} {
    return value == GuideTag.styling ? {
        styling: null
    } : value == GuideTag.thinning ? {
        thinning: null
    } : value == GuideTag.scalpCare ? {
        scalpCare: null
    } : value == GuideTag.greyHair ? {
        greyHair: null
    } : value == GuideTag.products ? {
        products: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOrder): {
    byNewest: null;
} | {
    byRating: null;
} | {
    byPrice: null;
} | {
    byPopularity: null;
} {
    return value == SortOrder.byNewest ? {
        byNewest: null
    } : value == SortOrder.byRating ? {
        byRating: null
    } : value == SortOrder.byPrice ? {
        byPrice: null
    } : value == SortOrder.byPopularity ? {
        byPopularity: null
    } : value;
}
function to_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<GuideTag>): Array<_GuideTag> {
    return value.map((x)=>to_candid_GuideTag_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
